title: Tech Notes
description: Just some stuff
author: Eugene S
github: https://github.com/esimakin
about: Just a java/js developer
disqus_shortname: techstuff
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/eugenesmk"
    # - icon: fa-twitter
      # link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/esimakin/"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/1858859/eugenes"
    - icon: fa-github
      link: "https://github.com/esimakin"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    # - text: About Me
      # url: /about/
    # - text: My Projects
      # url: /projects/
    - text: XML Feed
      url: /feed.xml

url: ""
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
